# version: "3.8"

services:
  user-management-service:
    build:
      context: ./user-management-service
    container_name: user-management-service
    depends_on:
      - user-management-db
    ports:
      - "5001:5001"
    env_file:
      - user-management-db/.env
    networks:
      - main-network

  user-management-db:
    image: postgres:16
    env_file:
      - user-management-db/.env
    volumes:
      - user-management-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - main-network

  calendar-service:
    build:
      context: ./calendar-service
    container_name: calendar-service
    depends_on:
      - calendar-db
    env_file:
      - calendar-db/.env
    ports:
      - "5002:5002"
    networks:
      - main-network

  calendar-db:
    image: postgres:16
    env_file:
      - calendar-db/.env
    volumes:
      - calendar-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - main-network

  gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-management-service
      - calendar-service
      - redis
    networks:
      - main-network

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - main-network

networks:
  main-network:
    driver: bridge

volumes:
  user-management-data:
    driver: local
  calendar-data:
    driver: local
