# version: "2"

services:
  user-management-service:
    build:
      context: ./user-management-service
    depends_on:
      - user-management-db
    deploy:
      replicas: 3
    env_file:
      - user-management-db/.env
    networks:
      - main-network

  user-management-db:
    image: postgres:16
    env_file:
      - user-management-db/.env
    volumes:
      - user-management-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - main-network

  # calendar-service:
  #     build:
  #       context: ./calendar-service
  #     depends_on:
  #       - calendar-db
  #     env_file:
  #       - calendar-db/.env
  #     deploy:
  #       replicas: 3
  #     networks:
  #       - main-network

  calendar-service-1:
    build:
      context: ./calendar-service
    depends_on:
      - calendar-db
    env_file:
      - calendar-db/.env
    ports:
      - "5002:5002"
    networks:
      - main-network

  calendar-service-2:
    build:
      context: ./calendar-service
    depends_on:
      - calendar-db
    env_file:
      - calendar-db/.env
    ports:
      - "5003:5002"
    networks:
      - main-network

  calendar-service-3:
    build:
      context: ./calendar-service
    depends_on:
      - calendar-db
    env_file:
      - calendar-db/.env
    ports:
      - "5004:5002"
    networks:
      - main-network

  calendar-db:
    image: postgres:16
    env_file:
      - calendar-db/.env
    volumes:
      - calendar-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - main-network

  gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-management-service
      - calendar-service-1
      - calendar-service-2
      - calendar-service-3
      - redis
      - consul
    networks:
      - main-network

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - main-network

  consul:
    build: ./service-discovery
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      - main-network 

networks:
  main-network:
    driver: bridge

volumes:
  user-management-data:
    driver: local
  calendar-data:
    driver: local
