
services:
  user-management-service:
    build:
      context: ./user-management-service
    depends_on:
      - user-management-db
      - logstash
    deploy:
      replicas: 3
    env_file:
      - user-management-db/.env
    environment:
      - LOG_HOST=logstash
    networks:
      - main-network

  user-management-db:
    image: postgres:16
    env_file:
      - user-management-db/.env
    volumes:
      - user-management-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - main-network

  # user-management-db-2:
  #   image: postgres:16
  #   env_file:
  #     - user-management-db/.env2
  #   volumes:
  #     - user-management-data:/var/lib/postgresql/data
  #   ports:
  #     - "5434:5432"
  #   networks:
  #     - main-network

  # user-management-db-3:
  #   image: postgres:16
  #   env_file:
  #     - user-management-db/.env3
  #   volumes:
  #     - user-management-data:/var/lib/postgresql/data
  #   ports:
  #     - "5435:5432"
  #   networks:
  #     - main-network

  # calendar-service:
  #     build:
  #       context: ./calendar-service
  #     depends_on:
  #       - calendar-db
  #     env_file:
  #       - calendar-db/.env
  #     deploy:
  #       replicas: 3
  #     networks:
  #       - main-network

  calendar-service-1:
    build:
      context: ./calendar-service
    depends_on:
      - calendar-db
    env_file:
      - calendar-db/.env
    ports:
      - "5002:5002"
    networks:
      - main-network

  calendar-service-2:
    build:
      context: ./calendar-service
    depends_on:
      - calendar-db
    env_file:
      - calendar-db/.env
    ports:
      - "5003:5002"
    networks:
      - main-network

  calendar-service-3:
    build:
      context: ./calendar-service
    depends_on:
      - calendar-db
    env_file:
      - calendar-db/.env
    ports:
      - "5004:5002"
    networks:
      - main-network

  calendar-db:
    image: postgres:16
    env_file:
      - calendar-db/.env
    volumes:
      - calendar-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - main-network

  gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-management-service
      - calendar-service-1
      - calendar-service-2
      - calendar-service-3
      - redis
      - consul
    networks:
      - main-network

  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - main-network

  consul:
    build: ./service-discovery
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      - main-network 

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - main-network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
      - "9600:9600"
    networks:
      - main-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
    - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - main-network

  redis_node_a:
    image: redis:latest
    container_name: redis_node_a
    hostname: redis_node_a
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    networks:
      main-network:
        ipv4_address: 172.21.0.252

  redis_node_b:
    image: redis:latest
    container_name: redis_node_b
    ports:
      - "6381:6379"
    command: redis-server --appendonly yes
    networks:
      main-network:
        ipv4_address: 172.21.0.253

  redis_node_c:
    image: redis:latest
    container_name: redis_node_c
    ports:
      - "6382:6379"
    command: redis-server --appendonly yes
    networks:
      main-network:
        ipv4_address: 172.21.0.254

  sentinel_node_a:
    image: redis:latest
    depends_on:
      - redis_node_c
    ports:
      - "26379:26379"
    networks:
      - main-network
    volumes:
      - ./sentinel1.conf:/data/sentinel1.conf
    command: >
      redis-sentinel /data/sentinel1.conf --port 26379
    
  sentinel_node_b:
    image: redis:latest
    depends_on:
      - redis_node_b
    ports:
      - "26380:26379"
    networks:
      - main-network
    volumes:
      - ./sentinel2.conf:/data/sentinel2.conf
    command: >
      redis-sentinel /data/sentinel2.conf --port 26379 

  sentinel_node_c:
    image: redis:latest
    depends_on:
      - redis_node_c
    ports:
      - "26381:26379"
    networks:
      - main-network
    volumes:
      - ./sentinel3.conf:/data/sentinel3.conf
    command: >
      redis-sentinel /data/sentinel3.conf --port 26379

networks:
  main-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  user-management-data:
    driver: local
  calendar-data:
    driver: local
